package handler

import "github.com/gin-gonic/gin"

func WebService() *gin.Engine {
	router := gin.Default()
	api := router.Group("/api")
	appManager := new(AppManager)
	api.POST("/upload", appManager.UploadFile)
	user := api.Group("/user")
	user.GET("/info", appManager.UserInfo)
	user.POST("/register", appManager.Register)
	//user.POST("/login", appManager.Login)
	//user.POST("/send_code", appManager.SendCode)
	dingdiantui := api.Group("/dingdiantui")
	dingdiantui.POST("/order", appManager.CreateDingDianTui)
	//dingdiantui.GET("/orders", appManager.QueryDingDianTuis)
	//dingdiantui.GET("/order/:id", appManager.QueryDingDianTui)
	//dingdiantui.PUT("/order/:id", appManager.UpdateDingDianTui)
	//dingdiantui.DELETE("/order/:id", appManager.DeleteDingDianTui)
	keliujing := api.Group("/keliujing")
	keliujing.POST("/order", appManager.CreateKeLiuJing)
	//keliujing.GET("/orders", appManager.QueryKeLiuJings)
	//keliujing.GET("/order/:id", appManager.QueryKeLiuJing)
	//keliujing.PUT("/order/:id", appManager.UpdateKeLiuJing)
	//keliujing.DELETE("/order/:id", appManager.DeleteKeLiuJing)
	chaoshixin := api.Group("/chaoshixin")
	chaoshixin.POST("/order", appManager.CreateChaoShiXin)
	//chaoshixin.GET("/orders", appManager.QueryChaoShiXins)
	//chaoshixin.GET("/order/:id", appManager.QueryChaoShiXin)
	//chaoshixin.PUT("/order/:id", appManager.UpdateChaoShiXin)
	//chaoshixin.DELETE("/order/:id", appManager.DeleteChaoShiXin)
	aiyunhu := api.Group("/aiyunhu")
	aiyunhu.POST("/order", appManager.CreateAIYunHu)
	//aiyunhu.GET("/orders", appManager.QueryAIYunHus)
	//aiyunhu.GET("/order/:id", appManager.QueryAIYunHu)
	//aiyunhu.PUT("/order/:id", appManager.UpdateAIYunHu)
	//aiyunhu.DELETE("/order/:id", appManager.DeleteAIYunHu)
	pinxiaotong := api.Group("/pinxiaotong")
	pinxiaotong.POST("/order", appManager.CreatePinXiaoTong)
	//pinxiaotong.GET("/orders", appManager.QueryPinXiaoTongs)
	//pinxiaotong.GET("/order/:id", appManager.QueryPinXiaoTong)
	//pinxiaotong.PUT("/order/:id", appManager.UpdatePinXiaoTong)
	//pinxiaotong.DELETE("/order/:id", appManager.DeletePinXiaoTong)
	cheshichuang := api.Group("/cheshichuang")
	cheshichuang.POST("/order", appManager.CreateCheShiChuang)
	//cheshichuang.GET("/orders", appManager.QueryPinXiaoTongs)
	//cheshichuang.GET("/order/:id", appManager.QueryPinXiaoTong)
	//cheshichuang.PUT("/order/:id", appManager.UpdatePinXiaoTong)
	//cheshichuang.DELETE("/order/:id", appManager.DeletePinXiaoTong)
	waqianke := api.Group("/waqianke")
	waqianke.POST("/order", appManager.CreateWaQianKe)
	//waqianke.GET("/orders", appManager.QueryPinXiaoTongs)
	//waqianke.GET("/order/:id", appManager.QueryPinXiaoTong)
	//waqianke.PUT("/order/:id", appManager.UpdatePinXiaoTong)
	//waqianke.DELETE("/order/:id", appManager.DeletePinXiaoTong)
	yunhuaxiang := api.Group("/yunhuaxiang")
	yunhuaxiang.POST("/order", appManager.CreateYunHuaXiang)
	//yunhuaxiang.GET("/orders", appManager.QueryPinXiaoTongs)
	//yunhuaxiang.GET("/order/:id", appManager.QueryPinXiaoTong)
	//yunhuaxiang.PUT("/order/:id", appManager.UpdatePinXiaoTong)
	//yunhuaxiang.DELETE("/order/:id", appManager.DeletePinXiaoTong)
	return router
}
