// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package goMicro_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderInfo struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	HoldTime             string   `protobuf:"bytes,2,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	PreheatTime          string   `protobuf:"bytes,3,opt,name=preheat_time,json=preheatTime,proto3" json:"preheat_time,omitempty"`
	PushRange            string   `protobuf:"bytes,4,opt,name=push_range,json=pushRange,proto3" json:"push_range,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *OrderInfo) GetHoldTime() string {
	if m != nil {
		return m.HoldTime
	}
	return ""
}

func (m *OrderInfo) GetPreheatTime() string {
	if m != nil {
		return m.PreheatTime
	}
	return ""
}

func (m *OrderInfo) GetPushRange() string {
	if m != nil {
		return m.PushRange
	}
	return ""
}

func (m *OrderInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OrderInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderInfo)(nil), "goMicro.srv.order.OrderInfo")
	proto.RegisterType((*Response)(nil), "goMicro.srv.order.Response")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0xb1, 0xa9, 0xcd, 0x54, 0x04, 0x17, 0x91, 0xa5, 0x55, 0xd0, 0x9e, 0x3c, 0xe5, 0xa0,
	0x3f, 0xa1, 0x82, 0xf5, 0x50, 0xd4, 0xa0, 0xe7, 0x12, 0xbb, 0xd3, 0x66, 0x31, 0xdd, 0x59, 0x66,
	0xb7, 0x82, 0xff, 0xc9, 0x1f, 0xe8, 0x51, 0xb2, 0x89, 0xf1, 0xa0, 0xb7, 0x78, 0x9b, 0xf7, 0xc1,
	0xe3, 0xed, 0x63, 0x21, 0xc9, 0xad, 0x4d, 0x2d, 0x93, 0x27, 0x71, 0xb4, 0xa1, 0x85, 0x5e, 0x31,
	0xa5, 0x8e, 0xdf, 0x52, 0x62, 0x85, 0x3c, 0xfd, 0xe8, 0x41, 0x72, 0x5f, 0x5d, 0x77, 0x66, 0x4d,
	0x62, 0x0c, 0xc3, 0x92, 0x56, 0xb9, 0xd7, 0x64, 0x64, 0xef, 0xbc, 0x77, 0x99, 0x64, 0x2d, 0x16,
	0x13, 0x48, 0x0a, 0x2a, 0xd5, 0xd2, 0xeb, 0x2d, 0xca, 0xa8, 0x16, 0x2b, 0xe2, 0x49, 0x6f, 0x51,
	0x5c, 0xc0, 0x81, 0x65, 0x2c, 0x30, 0xf7, 0xb5, 0xbe, 0x17, 0xf4, 0x51, 0xc3, 0x05, 0xcb, 0x19,
	0x80, 0xdd, 0xb9, 0x62, 0xc9, 0xb9, 0xd9, 0xa0, 0xec, 0x07, 0x43, 0x52, 0x31, 0x59, 0x45, 0x88,
	0x63, 0x88, 0x3d, 0xbd, 0xa2, 0x91, 0x71, 0x50, 0x6a, 0x20, 0x0e, 0x21, 0xd2, 0x4a, 0x0e, 0x02,
	0x15, 0x69, 0x35, 0x7d, 0x80, 0x61, 0x86, 0xce, 0x92, 0x71, 0x28, 0x24, 0xec, 0x23, 0xf3, 0x8c,
	0x14, 0x86, 0xae, 0x71, 0xf6, 0x0d, 0xc5, 0x09, 0x0c, 0x90, 0x79, 0xe1, 0x36, 0x4d, 0xcf, 0x06,
	0x09, 0x01, 0x7d, 0x6d, 0xd6, 0xd4, 0xb4, 0x0b, 0xf7, 0xd5, 0x67, 0x04, 0x71, 0x18, 0x40, 0xcc,
	0x61, 0x34, 0x63, 0xcc, 0x3d, 0xd6, 0xf0, 0x34, 0xfd, 0xb5, 0x56, 0xda, 0x2e, 0x35, 0x9e, 0xfc,
	0xa1, 0xb6, 0xcd, 0xe6, 0x30, 0x7a, 0xdc, 0x21, 0xbf, 0x07, 0xbb, 0xeb, 0x92, 0x74, 0x0b, 0xf0,
	0x93, 0xd4, 0xb1, 0xd2, 0xb3, 0x55, 0xff, 0xf4, 0xb8, 0x1b, 0x2c, 0xb1, 0x7b, 0xd2, 0xcb, 0x20,
	0xfc, 0xca, 0xeb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x96, 0x2d, 0xdc, 0xa2, 0x02, 0x00,
	0x00,
}
