// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package goMicro_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DingDianTuiInfo struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	HoldTime             string   `protobuf:"bytes,2,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	PreheatTime          string   `protobuf:"bytes,3,opt,name=preheat_time,json=preheatTime,proto3" json:"preheat_time,omitempty"`
	PushRange            string   `protobuf:"bytes,4,opt,name=push_range,json=pushRange,proto3" json:"push_range,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DingDianTuiInfo) Reset()         { *m = DingDianTuiInfo{} }
func (m *DingDianTuiInfo) String() string { return proto.CompactTextString(m) }
func (*DingDianTuiInfo) ProtoMessage()    {}
func (*DingDianTuiInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *DingDianTuiInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DingDianTuiInfo.Unmarshal(m, b)
}
func (m *DingDianTuiInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DingDianTuiInfo.Marshal(b, m, deterministic)
}
func (m *DingDianTuiInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DingDianTuiInfo.Merge(m, src)
}
func (m *DingDianTuiInfo) XXX_Size() int {
	return xxx_messageInfo_DingDianTuiInfo.Size(m)
}
func (m *DingDianTuiInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DingDianTuiInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DingDianTuiInfo proto.InternalMessageInfo

func (m *DingDianTuiInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *DingDianTuiInfo) GetHoldTime() string {
	if m != nil {
		return m.HoldTime
	}
	return ""
}

func (m *DingDianTuiInfo) GetPreheatTime() string {
	if m != nil {
		return m.PreheatTime
	}
	return ""
}

func (m *DingDianTuiInfo) GetPushRange() string {
	if m != nil {
		return m.PushRange
	}
	return ""
}

func (m *DingDianTuiInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DingDianTuiInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DingDianTuiInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type KeLiuJingInfo struct {
	MonitorArea          string   `protobuf:"bytes,1,opt,name=monitor_area,json=monitorArea,proto3" json:"monitor_area,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeLiuJingInfo) Reset()         { *m = KeLiuJingInfo{} }
func (m *KeLiuJingInfo) String() string { return proto.CompactTextString(m) }
func (*KeLiuJingInfo) ProtoMessage()    {}
func (*KeLiuJingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *KeLiuJingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeLiuJingInfo.Unmarshal(m, b)
}
func (m *KeLiuJingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeLiuJingInfo.Marshal(b, m, deterministic)
}
func (m *KeLiuJingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeLiuJingInfo.Merge(m, src)
}
func (m *KeLiuJingInfo) XXX_Size() int {
	return xxx_messageInfo_KeLiuJingInfo.Size(m)
}
func (m *KeLiuJingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KeLiuJingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KeLiuJingInfo proto.InternalMessageInfo

func (m *KeLiuJingInfo) GetMonitorArea() string {
	if m != nil {
		return m.MonitorArea
	}
	return ""
}

func (m *KeLiuJingInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *KeLiuJingInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeLiuJingInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *KeLiuJingInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *KeLiuJingInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ChaoShiXinInfo struct {
	SendNum              string   `protobuf:"bytes,1,opt,name=send_num,json=sendNum,proto3" json:"send_num,omitempty"`
	SendTime             string   `protobuf:"bytes,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Theme                string   `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	Clew                 string   `protobuf:"bytes,4,opt,name=clew,proto3" json:"clew,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaoShiXinInfo) Reset()         { *m = ChaoShiXinInfo{} }
func (m *ChaoShiXinInfo) String() string { return proto.CompactTextString(m) }
func (*ChaoShiXinInfo) ProtoMessage()    {}
func (*ChaoShiXinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *ChaoShiXinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaoShiXinInfo.Unmarshal(m, b)
}
func (m *ChaoShiXinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaoShiXinInfo.Marshal(b, m, deterministic)
}
func (m *ChaoShiXinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaoShiXinInfo.Merge(m, src)
}
func (m *ChaoShiXinInfo) XXX_Size() int {
	return xxx_messageInfo_ChaoShiXinInfo.Size(m)
}
func (m *ChaoShiXinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaoShiXinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChaoShiXinInfo proto.InternalMessageInfo

func (m *ChaoShiXinInfo) GetSendNum() string {
	if m != nil {
		return m.SendNum
	}
	return ""
}

func (m *ChaoShiXinInfo) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *ChaoShiXinInfo) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func (m *ChaoShiXinInfo) GetClew() string {
	if m != nil {
		return m.Clew
	}
	return ""
}

func (m *ChaoShiXinInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ChaoShiXinInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChaoShiXinInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AIYunHuInfo struct {
	DialNum              string   `protobuf:"bytes,1,opt,name=dial_num,json=dialNum,proto3" json:"dial_num,omitempty"`
	DialTime             string   `protobuf:"bytes,2,opt,name=dial_time,json=dialTime,proto3" json:"dial_time,omitempty"`
	Theme                string   `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	Clew                 string   `protobuf:"bytes,4,opt,name=clew,proto3" json:"clew,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AIYunHuInfo) Reset()         { *m = AIYunHuInfo{} }
func (m *AIYunHuInfo) String() string { return proto.CompactTextString(m) }
func (*AIYunHuInfo) ProtoMessage()    {}
func (*AIYunHuInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *AIYunHuInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AIYunHuInfo.Unmarshal(m, b)
}
func (m *AIYunHuInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AIYunHuInfo.Marshal(b, m, deterministic)
}
func (m *AIYunHuInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AIYunHuInfo.Merge(m, src)
}
func (m *AIYunHuInfo) XXX_Size() int {
	return xxx_messageInfo_AIYunHuInfo.Size(m)
}
func (m *AIYunHuInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AIYunHuInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AIYunHuInfo proto.InternalMessageInfo

func (m *AIYunHuInfo) GetDialNum() string {
	if m != nil {
		return m.DialNum
	}
	return ""
}

func (m *AIYunHuInfo) GetDialTime() string {
	if m != nil {
		return m.DialTime
	}
	return ""
}

func (m *AIYunHuInfo) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func (m *AIYunHuInfo) GetClew() string {
	if m != nil {
		return m.Clew
	}
	return ""
}

func (m *AIYunHuInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AIYunHuInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AIYunHuInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Word struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Word) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Word) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Word) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type Response struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type LoginInfo struct {
	PhoneNum             string   `protobuf:"bytes,1,opt,name=phone_num,json=phoneNum,proto3" json:"phone_num,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{6}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *LoginInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LoginInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func init() {
	proto.RegisterType((*DingDianTuiInfo)(nil), "goMicro.srv.order.DingDianTuiInfo")
	proto.RegisterType((*KeLiuJingInfo)(nil), "goMicro.srv.order.KeLiuJingInfo")
	proto.RegisterType((*ChaoShiXinInfo)(nil), "goMicro.srv.order.ChaoShiXinInfo")
	proto.RegisterType((*AIYunHuInfo)(nil), "goMicro.srv.order.AIYunHuInfo")
	proto.RegisterType((*Word)(nil), "goMicro.srv.order.Word")
	proto.RegisterType((*Response)(nil), "goMicro.srv.order.Response")
	proto.RegisterType((*LoginInfo)(nil), "goMicro.srv.order.LoginInfo")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x4e, 0x13, 0x4f,
	0x14, 0x4f, 0x4b, 0x3f, 0x0f, 0x50, 0x60, 0xf2, 0xcf, 0xdf, 0x15, 0xd4, 0x40, 0xaf, 0xbc, 0xea,
	0x85, 0x3e, 0x01, 0x82, 0x89, 0x48, 0x11, 0x28, 0x35, 0xea, 0x85, 0x69, 0x46, 0xe6, 0xb0, 0x3b,
	0xb1, 0x9d, 0xd9, 0xcc, 0xec, 0x62, 0xb8, 0xf3, 0x41, 0x7c, 0x03, 0x13, 0x9f, 0xc3, 0xc7, 0x32,
	0xf3, 0xd1, 0xed, 0x02, 0x1b, 0x9b, 0xb8, 0xab, 0x77, 0x73, 0x3e, 0xe6, 0x77, 0x7e, 0xe7, 0x77,
	0x76, 0x66, 0x16, 0xba, 0x34, 0x8e, 0x07, 0xb1, 0x92, 0x89, 0x24, 0x5b, 0xa1, 0x3c, 0xe1, 0x97,
	0x4a, 0x0e, 0xb4, 0xba, 0x1e, 0x48, 0xc5, 0x50, 0xf5, 0x7f, 0xd6, 0x60, 0xe3, 0x90, 0x8b, 0xf0,
	0x90, 0x53, 0x31, 0x4e, 0xf9, 0x91, 0xb8, 0x92, 0x64, 0x1b, 0x3a, 0x53, 0x79, 0x49, 0x13, 0x2e,
	0x45, 0x50, 0xdb, 0xad, 0x3d, 0xed, 0x8e, 0x32, 0x9b, 0xec, 0x40, 0x37, 0x92, 0x53, 0x36, 0x49,
	0xf8, 0x0c, 0x83, 0xba, 0x0b, 0x1a, 0xc7, 0x98, 0xcf, 0x90, 0xec, 0xc1, 0x5a, 0xac, 0x30, 0x42,
	0x9a, 0xb8, 0xf8, 0x8a, 0x8d, 0xaf, 0x7a, 0x9f, 0x4d, 0x79, 0x0c, 0x10, 0xa7, 0x3a, 0x9a, 0x28,
	0x2a, 0x42, 0x0c, 0x1a, 0x36, 0xa1, 0x6b, 0x3c, 0x23, 0xe3, 0x20, 0xff, 0x41, 0x33, 0x8e, 0xa4,
	0xc0, 0xa0, 0x69, 0x23, 0xce, 0x30, 0xde, 0x44, 0x7e, 0x46, 0x11, 0xb4, 0x9c, 0xd7, 0x1a, 0xa4,
	0x07, 0x75, 0xce, 0x82, 0xb6, 0x75, 0xd5, 0x39, 0xeb, 0x7f, 0xab, 0xc1, 0xfa, 0x31, 0x0e, 0x79,
	0xfa, 0x9a, 0x8b, 0xd0, 0x36, 0xb2, 0x07, 0x6b, 0x33, 0x29, 0x78, 0x22, 0xd5, 0x84, 0x2a, 0xa4,
	0xbe, 0x99, 0x55, 0xef, 0xdb, 0x57, 0x48, 0x49, 0x00, 0xed, 0x6b, 0x54, 0xda, 0xb4, 0xea, 0xba,
	0x99, 0x9b, 0x84, 0x40, 0x43, 0xd0, 0xac, 0x09, 0xbb, 0x5e, 0xd0, 0x6b, 0x14, 0xd2, 0x6b, 0xde,
	0xa7, 0xd7, 0xca, 0xe8, 0xfd, 0xa8, 0x41, 0xef, 0x20, 0xa2, 0xf2, 0x22, 0xe2, 0xef, 0xb9, 0xb0,
	0xfc, 0x1e, 0x42, 0x47, 0xa3, 0x60, 0x13, 0x91, 0xce, 0x3c, 0xb7, 0xb6, 0xb1, 0xdf, 0xa4, 0x33,
	0xa3, 0xb3, 0x0d, 0xe5, 0x75, 0x36, 0x0e, 0x2b, 0xa2, 0x29, 0x18, 0x61, 0xc6, 0xcd, 0x19, 0x86,
	0xf0, 0xe5, 0x14, 0xbf, 0x78, 0x6e, 0x76, 0x5d, 0x4a, 0xcf, 0xef, 0x35, 0x58, 0xdd, 0x3f, 0xfa,
	0x90, 0x8a, 0x57, 0xe9, 0x9c, 0x2d, 0xe3, 0x74, 0x9a, 0x67, 0x6b, 0x6c, 0xcf, 0xd6, 0x86, 0xf2,
	0x6c, 0x8d, 0xe3, 0x1f, 0xb2, 0xfd, 0x08, 0x8d, 0x77, 0x52, 0x31, 0x83, 0x9b, 0xdc, 0xc4, 0xe8,
	0x19, 0xda, 0x35, 0x79, 0x00, 0xed, 0x54, 0xa3, 0x9a, 0x70, 0xe6, 0xc9, 0xb5, 0x8c, 0x79, 0xc4,
	0x16, 0x05, 0x57, 0xf2, 0x05, 0x09, 0x34, 0xb8, 0xb8, 0x92, 0x73, 0x6a, 0x66, 0xdd, 0x3f, 0x83,
	0xce, 0x08, 0x75, 0x2c, 0x85, 0x46, 0xf3, 0xcd, 0xa0, 0x52, 0x07, 0x92, 0xb9, 0x2a, 0xcd, 0xd1,
	0xdc, 0x24, 0xff, 0x43, 0x0b, 0x95, 0x3a, 0xd1, 0xe1, 0xbc, 0x8e, 0xb3, 0x32, 0xc4, 0x95, 0x1c,
	0xe2, 0x10, 0xba, 0x43, 0x19, 0xfa, 0x2f, 0x61, 0x07, 0xba, 0xb6, 0x76, 0x4e, 0xdc, 0x8e, 0x75,
	0x18, 0x75, 0x8d, 0x54, 0xa6, 0x58, 0xdd, 0x4b, 0x65, 0x2a, 0x99, 0xf6, 0x63, 0x8f, 0x57, 0xe7,
	0xf1, 0xb3, 0xaf, 0x3d, 0x68, 0x9e, 0x9a, 0x13, 0x4d, 0xc6, 0xb0, 0x75, 0xa0, 0x90, 0x26, 0x98,
	0x3b, 0xd6, 0xa4, 0x3f, 0xb8, 0x77, 0xf4, 0x07, 0x77, 0x8e, 0xfd, 0xf6, 0x4e, 0x41, 0x4e, 0xd6,
	0xf3, 0x18, 0xb6, 0xce, 0x53, 0x54, 0x37, 0xb9, 0x4d, 0xba, 0x3c, 0xea, 0x05, 0x6c, 0xde, 0x45,
	0xad, 0x84, 0xea, 0xdb, 0x98, 0xfd, 0x05, 0x01, 0x0e, 0x71, 0x8a, 0x15, 0xa3, 0x9e, 0xc1, 0x86,
	0x1b, 0x56, 0x76, 0x71, 0x91, 0xdd, 0x82, 0xfc, 0x5b, 0xd7, 0xda, 0x52, 0x44, 0x2b, 0x69, 0xb6,
	0x45, 0x97, 0x45, 0x3c, 0x85, 0xde, 0x6d, 0xc4, 0x0a, 0x28, 0xba, 0x01, 0x55, 0x89, 0xe8, 0x86,
	0x53, 0x19, 0xe2, 0x08, 0x36, 0xdd, 0x60, 0x16, 0x57, 0x36, 0xd9, 0x2b, 0xd8, 0x70, 0xfb, 0x46,
	0x5f, 0x8a, 0x69, 0x85, 0x5c, 0xec, 0xd1, 0xa5, 0x31, 0xcf, 0xfd, 0xb8, 0xab, 0xa5, 0xe9, 0xc6,
	0x53, 0x2d, 0xa6, 0x1b, 0x50, 0x85, 0x98, 0x43, 0x58, 0x77, 0x23, 0xf2, 0x8f, 0x14, 0x79, 0x52,
	0x90, 0x9d, 0x7b, 0xc0, 0x96, 0xa2, 0x59, 0x21, 0xfd, 0x06, 0x5d, 0x0e, 0xed, 0x18, 0xd6, 0xf2,
	0x68, 0xa5, 0xa9, 0xb9, 0x81, 0x54, 0x85, 0xe6, 0x46, 0x51, 0x09, 0xda, 0x0b, 0x68, 0xda, 0x57,
	0x8c, 0x3c, 0x2a, 0xc8, 0xca, 0xde, 0xb7, 0xdf, 0x63, 0xbc, 0x84, 0xce, 0x05, 0x0a, 0x66, 0x5f,
	0xd0, 0x3f, 0x87, 0xf9, 0xd4, 0xb2, 0x3f, 0xb9, 0xcf, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x4f,
	0x95, 0xee, 0x30, 0xf1, 0x0a, 0x00, 0x00,
}
