// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: app.proto

package goMicro_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Order service

type OrderService interface {
	CreateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error)
	QueryOrders(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error)
	QueryOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error)
	UpdateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error)
	DeleteOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error)
	Login(ctx context.Context, in *LoginInfo, opts ...client.CallOption) (*Response, error)
	SendCode(ctx context.Context, in *LoginInfo, opts ...client.CallOption) (*Response, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "goMicro.srv.order"
	}
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) CreateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.CreateOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) QueryOrders(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.QueryOrders", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) QueryOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.QueryOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) UpdateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.UpdateOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) DeleteOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.DeleteOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Login(ctx context.Context, in *LoginInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.Login", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) SendCode(ctx context.Context, in *LoginInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.SendCode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	CreateOrder(context.Context, *OrderInfo, *Response) error
	QueryOrders(context.Context, *OrderInfo, *Response) error
	QueryOrder(context.Context, *OrderInfo, *Response) error
	UpdateOrder(context.Context, *OrderInfo, *Response) error
	DeleteOrder(context.Context, *OrderInfo, *Response) error
	Login(context.Context, *LoginInfo, *Response) error
	SendCode(context.Context, *LoginInfo, *Response) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		CreateOrder(ctx context.Context, in *OrderInfo, out *Response) error
		QueryOrders(ctx context.Context, in *OrderInfo, out *Response) error
		QueryOrder(ctx context.Context, in *OrderInfo, out *Response) error
		UpdateOrder(ctx context.Context, in *OrderInfo, out *Response) error
		DeleteOrder(ctx context.Context, in *OrderInfo, out *Response) error
		Login(ctx context.Context, in *LoginInfo, out *Response) error
		SendCode(ctx context.Context, in *LoginInfo, out *Response) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) CreateOrder(ctx context.Context, in *OrderInfo, out *Response) error {
	return h.OrderHandler.CreateOrder(ctx, in, out)
}

func (h *orderHandler) QueryOrders(ctx context.Context, in *OrderInfo, out *Response) error {
	return h.OrderHandler.QueryOrders(ctx, in, out)
}

func (h *orderHandler) QueryOrder(ctx context.Context, in *OrderInfo, out *Response) error {
	return h.OrderHandler.QueryOrder(ctx, in, out)
}

func (h *orderHandler) UpdateOrder(ctx context.Context, in *OrderInfo, out *Response) error {
	return h.OrderHandler.UpdateOrder(ctx, in, out)
}

func (h *orderHandler) DeleteOrder(ctx context.Context, in *OrderInfo, out *Response) error {
	return h.OrderHandler.DeleteOrder(ctx, in, out)
}

func (h *orderHandler) Login(ctx context.Context, in *LoginInfo, out *Response) error {
	return h.OrderHandler.Login(ctx, in, out)
}

func (h *orderHandler) SendCode(ctx context.Context, in *LoginInfo, out *Response) error {
	return h.OrderHandler.SendCode(ctx, in, out)
}
